# Generated by Django 3.1.3 on 2020-11-28 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_reason',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='registration_reason',
            field=models.TextField(default='', verbose_name='Причина регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Пользователь активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('819434fd-55e3-43da-8baa-4486595b4906'), editable=False),
        ),
    ]
