# Generated by Django 3.1.3 on 2020-11-28 13:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 11, 28, 13, 1, 16, 358931, tzinfo=utc), editable=False)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Безопасная модель',
                'verbose_name_plural': 'Безопасные модели',
                'db_table': 'safe_model',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('safemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.safemodel')),
                ('file', models.FileField(upload_to='')),
            ],
            bases=('core.safemodel',),
        ),
    ]
