# Generated by Django 3.1.3 on 2020-11-28 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 28, 14, 49, 13, 289432, tzinfo=utc), editable=False),
        ),
    ]
